/**
 * GitHub Issues — Issue CRUD, lifecycle, batch operations, and branch naming
 *
 * Provides all issue-related operations: creating task issues with full spec bodies,
 * parent tracking issues with live task lists, todo issues, comments, close/reopen,
 * import external issues, supersession handling, and branch naming.
 *
 * Uses `ghExec` from gh.ts for all GitHub CLI operations.
 * Uses mapping.ts for persisting issue-to-task associations.
 *
 * CRITICAL: `gh issue create` does NOT support --format json.
 *   Parse the URL from stdout to extract issue number.
 * CRITICAL: Never call process.exit() — return GhResult instead.
 * CRITICAL: Never import octokit or any npm GitHub SDK.
 */

import type { GhResult } from './types.js';
import { ghExec } from './gh.js';

// ---- Helpers ---------------------------------------------------------------

/**
 * Parse an issue number from a `gh issue create` stdout URL.
 *
 * `gh issue create` outputs a URL like:
 *   https://github.com/owner/repo/issues/42\n
 *
 * We trim whitespace and extract the last path segment as the issue number.
 */
function parseIssueNumberFromUrl(stdout: string): number | null {
  const trimmed = stdout.trim();
  const lastSegment = trimmed.split('/').pop();
  if (!lastSegment) return null;
  const num = parseInt(lastSegment, 10);
  return Number.isNaN(num) ? null : num;
}

/**
 * After creating an issue (parsed number from URL), fetch its node_id
 * via `gh issue view {number} --json nodeId,number,url`.
 */
async function fetchIssueDetails(
  issueNumber: number,
): Promise<GhResult<{ number: number; url: string; node_id: string }>> {
  const result = await ghExec<{ nodeId: string; number: number; url: string }>(
    ['issue', 'view', String(issueNumber), '--json', 'nodeId,number,url'],
    { parseJson: true },
  );

  if (!result.ok) return { ok: false, error: result.error, code: result.code };

  return {
    ok: true,
    data: {
      number: result.data.number,
      url: result.data.url,
      node_id: result.data.nodeId,
    },
  };
}

// ---- Issue Creation Functions -----------------------------------------------

/**
 * Create a task issue with full specification body in collapsible details section.
 *
 * Title format: `[P{phaseNum}] {title}`
 * Body includes summary, actions, acceptance criteria, dependencies in `<details>`.
 * Labels: maxsim, phase-task.
 *
 * Returns the issue number, URL, and node_id.
 */
export async function createTaskIssue(opts: {
  title: string;
  phaseNum: string;
  planNum: string;
  taskId: string;
  summary: string;
  actions: string[];
  acceptanceCriteria: string[];
  dependencies?: number[];
  milestone?: string;
  projectTitle?: string;
  labels?: string[];
  estimate?: number;
}): Promise<GhResult<{ number: number; url: string; node_id: string }>> {
  const issueTitle = `[P${opts.phaseNum}] ${opts.title}`;

  // Build the issue body with collapsible details section
  const depsSection =
    opts.dependencies && opts.dependencies.length > 0
      ? `\n### Dependencies\nDepends on: ${opts.dependencies.map(d => `#${d}`).join(', ')}\n`
      : '';

  const estimateSection =
    opts.estimate !== undefined ? `\n### Estimate\n${opts.estimate} points\n` : '';

  const body = `## Summary
${opts.summary}

<details>
<summary>Full Specification</summary>

### Actions
${opts.actions.map(a => `- ${a}`).join('\n')}

### Acceptance Criteria
${opts.acceptanceCriteria.map(c => `- [ ] ${c}`).join('\n')}
${depsSection}${estimateSection}
</details>

---
*Phase: ${opts.phaseNum} | Plan: ${opts.planNum} | Task: ${opts.taskId}*
*Generated by MAXSIM*`;

  // Build gh issue create args
  const args: string[] = ['issue', 'create', '--title', issueTitle, '--body', body];

  // Always add maxsim and phase-task labels
  args.push('--label', 'maxsim');
  args.push('--label', 'phase-task');

  // Add any additional labels
  if (opts.labels) {
    for (const label of opts.labels) {
      args.push('--label', label);
    }
  }

  // Optional milestone
  if (opts.milestone) {
    args.push('--milestone', opts.milestone);
  }

  // Optional project
  if (opts.projectTitle) {
    args.push('--project', opts.projectTitle);
  }

  // Create the issue — stdout is a URL, NOT JSON
  const createResult = await ghExec<string>(args);
  if (!createResult.ok) return { ok: false, error: createResult.error, code: createResult.code };

  // Parse issue number from URL
  const issueNumber = parseIssueNumberFromUrl(createResult.data);
  if (issueNumber === null) {
    return {
      ok: false,
      error: `Failed to parse issue number from gh output: ${createResult.data}`,
      code: 'UNKNOWN',
    };
  }

  // Fetch node_id via separate gh issue view call
  return fetchIssueDetails(issueNumber);
}

/**
 * Create a parent tracking issue for a phase with a live checkbox task list.
 *
 * Title format: `[Phase {phaseNum}] {phaseName}`
 * Body includes task list with checkbox links: `- [ ] #{childNumber}`
 * Labels: maxsim, phase-task.
 */
export async function createParentTrackingIssue(opts: {
  phaseNum: string;
  phaseName: string;
  childIssueNumbers: number[];
  milestone?: string;
  projectTitle?: string;
}): Promise<GhResult<{ number: number; url: string; node_id: string }>> {
  const issueTitle = `[Phase ${opts.phaseNum}] ${opts.phaseName}`;

  const taskList = opts.childIssueNumbers.map(n => `- [ ] #${n}`).join('\n');

  const body = `## Phase ${opts.phaseNum}: ${opts.phaseName}

### Tasks
${taskList}

---
*Phase tracking issue -- Generated by MAXSIM*`;

  const args: string[] = ['issue', 'create', '--title', issueTitle, '--body', body];
  args.push('--label', 'maxsim');
  args.push('--label', 'phase-task');

  if (opts.milestone) {
    args.push('--milestone', opts.milestone);
  }

  if (opts.projectTitle) {
    args.push('--project', opts.projectTitle);
  }

  const createResult = await ghExec<string>(args);
  if (!createResult.ok) return { ok: false, error: createResult.error, code: createResult.code };

  const issueNumber = parseIssueNumberFromUrl(createResult.data);
  if (issueNumber === null) {
    return {
      ok: false,
      error: `Failed to parse issue number from gh output: ${createResult.data}`,
      code: 'UNKNOWN',
    };
  }

  return fetchIssueDetails(issueNumber);
}

/**
 * Create a todo issue with a lighter body (no collapsible details section).
 *
 * Labels: maxsim, todo.
 */
export async function createTodoIssue(opts: {
  title: string;
  description?: string;
  acceptanceCriteria?: string[];
  milestone?: string;
  projectTitle?: string;
}): Promise<GhResult<{ number: number; url: string; node_id: string }>> {
  let body = '';

  if (opts.description) {
    body += `${opts.description}\n`;
  }

  if (opts.acceptanceCriteria && opts.acceptanceCriteria.length > 0) {
    body += `\n### Acceptance Criteria\n`;
    body += opts.acceptanceCriteria.map(c => `- [ ] ${c}`).join('\n');
    body += '\n';
  }

  body += `\n---\n*Generated by MAXSIM*`;

  const args: string[] = ['issue', 'create', '--title', opts.title, '--body', body];
  args.push('--label', 'maxsim');
  args.push('--label', 'todo');

  if (opts.milestone) {
    args.push('--milestone', opts.milestone);
  }

  if (opts.projectTitle) {
    args.push('--project', opts.projectTitle);
  }

  const createResult = await ghExec<string>(args);
  if (!createResult.ok) return { ok: false, error: createResult.error, code: createResult.code };

  const issueNumber = parseIssueNumberFromUrl(createResult.data);
  if (issueNumber === null) {
    return {
      ok: false,
      error: `Failed to parse issue number from gh output: ${createResult.data}`,
      code: 'UNKNOWN',
    };
  }

  return fetchIssueDetails(issueNumber);
}

// ---- Utility Functions (pure/simple) ----------------------------------------

/**
 * Get the branch name for an issue.
 *
 * Format: `maxsim/issue-{issueNumber}-{slug}`
 * Pure function, no async needed.
 */
export function getIssueBranchName(issueNumber: number, slug: string): string {
  return `maxsim/issue-${issueNumber}-${slug}`;
}

/**
 * Build a PR description body with `Closes #{N}` lines for auto-close on merge (AC-08).
 *
 * This function is called by `mcp_create_pr` in Plan 04's github-tools.ts.
 */
export function buildPrBody(closesIssues: number[], additionalContent?: string): string {
  const closesLines = closesIssues.map(n => `Closes #${n}`).join('\n');
  const content = additionalContent ? `\n\n${additionalContent}` : '';
  return `${closesLines}${content}`;
}
