/**
 * GitHub Issue Templates — Template file generation
 *
 * Installs GitHub Issue Form YAML templates into `.github/ISSUE_TEMPLATE/`
 * for the MAXSIM-managed issue types: phase tasks and todos.
 *
 * These are file-system operations only (no gh CLI needed).
 * Uses synchronous fs to match existing core module patterns.
 *
 * CRITICAL: Never call process.exit().
 */

import fs from 'node:fs';
import path from 'node:path';

// ---- Template Content ------------------------------------------------------

/**
 * Phase task issue template (GitHub Issue Forms YAML format).
 *
 * Used for issues created from MAXSIM phase plans.
 * Labels: phase, task
 */
const PHASE_TASK_TEMPLATE = `name: "MAXSIM Phase Task"
description: "Task generated by MAXSIM phase planning"
labels: ["phase", "task"]
body:
  - type: markdown
    attributes:
      value: |
        This issue was auto-generated by MAXSIM.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Task summary
    validations:
      required: true

  - type: textarea
    id: spec
    attributes:
      label: Full Specification
      description: Detailed task specification including actions, criteria, and dependencies
`;

/**
 * Todo issue template (GitHub Issue Forms YAML format).
 *
 * Used for issues created from MAXSIM todo items.
 * Labels: task
 */
const TODO_TEMPLATE = `name: "MAXSIM Todo"
description: "Todo item tracked by MAXSIM"
labels: ["task"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of the todo item
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What defines "done" for this todo?
`;

// ---- Installation ----------------------------------------------------------

/**
 * Install MAXSIM issue templates into the project's `.github/ISSUE_TEMPLATE/` directory.
 *
 * Creates the directory recursively if it does not exist.
 * Writes two YAML files:
 *   - phase-task.yml (for phase plan tasks)
 *   - todo.yml (for todo items)
 *
 * Overwrites existing templates if present (to ensure latest version).
 * This is a synchronous file write operation (no gh CLI needed).
 */
export function installIssueTemplates(cwd: string): void {
  const templateDir = path.join(cwd, '.github', 'ISSUE_TEMPLATE');

  // Create directory recursively if it doesn't exist
  fs.mkdirSync(templateDir, { recursive: true });

  // Write phase task template
  fs.writeFileSync(
    path.join(templateDir, 'phase-task.yml'),
    PHASE_TASK_TEMPLATE,
    'utf-8',
  );

  // Write todo template
  fs.writeFileSync(
    path.join(templateDir, 'todo.yml'),
    TODO_TEMPLATE,
    'utf-8',
  );
}
